{% set name = "napari-stable-diffusion" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-stable-diffusion-{{ version }}.tar.gz
  sha256: f089c6253afc95a786318cf8cbedb5f78e738cc09162efe1df91bc811396af3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - diffusers
    - magicgui
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.8,<3.11
    - pytorch
    - qtpy    
    - transformers

test:
  imports:
    - napari_stable_diffusion
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kephale/napari-stable-diffusion
  summary: A demo of stable diffusion in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kephale
